#!/usr/bin/env python3
"""The one source of truth for the core's input wire order.

Emits guest/src/input_table.rs (what the guest injects for each button) and
prints the waterbox.config "input" section (what the frontend shows), so the
two can never drift. Run it after editing the table.

Buttons are LEVELS, as in every chimera core: a key held across frames is a
key held. The guest turns level changes into Ruffle's edge events (KeyDown,
KeyUp, MouseDown, MouseUp) at the start of each frame.
"""
import json, sys, os

# (name shown to the user, kind, payload)
#   kind "mouse": payload = Ruffle MouseButton variant
#   kind "char":  payload = (unshifted char, shifted char, PhysicalKey)
#   kind "named": payload = (NamedKey, PhysicalKey, KeyLocation)
#   kind "numch": payload = (char, PhysicalKey)   - numpad character, Numpad location
T = []
T += [("Mouse Left Button", "mouse", "Left"), ("Mouse Middle Button", "mouse", "Middle"),
      ("Mouse Right Button", "mouse", "Right")]
for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
    T.append((f"Key {c}", "char", (c.lower(), c, f"Key{c}")))
for d, s in zip("1234567890", "!@#$%^&*()"):
    T.append((f"Key {d}", "char", (d, s, f"Digit{d}")))
T += [("Key Space", "char", (" ", " ", "Space"))]
for name, nk, pk in [("Enter","Enter","Enter"),("Escape","Escape","Escape"),("Tab","Tab","Tab"),
                     ("Backspace","Backspace","Backspace"),("Delete","Delete","Delete"),
                     ("Insert","Insert","Insert"),("Home","Home","Home"),("End","End","End"),
                     ("Page Up","PageUp","PageUp"),("Page Down","PageDown","PageDown"),
                     ("Up","ArrowUp","ArrowUp"),("Down","ArrowDown","ArrowDown"),
                     ("Left","ArrowLeft","ArrowLeft"),("Right","ArrowRight","ArrowRight")]:
    T.append((f"Key {name}", "named", (nk, pk, "Standard")))
T += [("Key Left Shift", "named", ("Shift", "ShiftLeft", "Left")),
      ("Key Right Shift", "named", ("Shift", "ShiftRight", "Right")),
      ("Key Left Control", "named", ("Control", "ControlLeft", "Left")),
      ("Key Right Control", "named", ("Control", "ControlRight", "Right")),
      ("Key Left Alt", "named", ("Alt", "AltLeft", "Left")),
      ("Key Right Alt", "named", ("Alt", "AltRight", "Right")),
      ("Key Caps Lock", "named", ("CapsLock", "CapsLock", "Standard")),
      ("Key Num Lock", "named", ("NumLock", "NumLock", "Standard")),
      ("Key Scroll Lock", "named", ("ScrollLock", "ScrollLock", "Standard")),
      ("Key Pause", "named", ("Pause", "Pause", "Standard"))]
for i in range(1, 13):
    T.append((f"Key F{i}", "named", (f"F{i}", f"F{i}", "Standard")))
for name, u, s, pk in [("Minus","-","_","Minus"),("Equals","=","+","Equal"),
                       ("Left Bracket","[","{","BracketLeft"),("Right Bracket","]","}","BracketRight"),
                       ("Backslash","\\","|","Backslash"),("Semicolon",";",":","Semicolon"),
                       ("Quote","'",'"',"Quote"),("Comma",",","<","Comma"),("Period",".",">","Period"),
                       ("Slash","/","?","Slash"),("Backquote","`","~","Backquote")]:
    T.append((f"Key {name}", "char", (u, s, pk)))
for d in "0123456789":
    T.append((f"Numpad {d}", "numch", (d, f"Numpad{d}")))
for name, ch, pk in [("Add","+","NumpadAdd"),("Subtract","-","NumpadSubtract"),
                     ("Multiply","*","NumpadMultiply"),("Divide","/","NumpadDivide"),
                     ("Decimal",".","NumpadDecimal")]:
    T.append((f"Numpad {name}", "numch", (ch, pk)))
T += [("Numpad Enter", "named", ("Enter", "NumpadEnter", "Numpad"))]

AXES = [{"name": "Mouse X", "min": 0, "max": 8191, "neutral": 0},
        {"name": "Mouse Y", "min": 0, "max": 8191, "neutral": 0}]

def rs_char(c):
    return "'" + c.replace("\\", "\\\\").replace("'", "\\'") + "'"

def emit_rs(path):
    lines = ["// GENERATED by waterbox/input-table.py - do not edit; edit the table there.",
             "// One entry per button, in waterbox.config's wire order.",
             "use ruffle_core::events::{KeyLocation, MouseButton, NamedKey, PhysicalKey};",
             "",
             "pub enum Btn {",
             "    Mouse(MouseButton),",
             "    /// unshifted char, shifted char, physical key",
             "    Char(char, char, PhysicalKey),",
             "    Named(NamedKey, PhysicalKey, KeyLocation),",
             "    /// a numpad key that types a character",
             "    NumChar(char, PhysicalKey),",
             "}",
             "",
             f"pub const BUTTON_COUNT: usize = {len(T)};",
             "pub const SHIFT_LEFT: usize = %d;" % [i for i,(n,_,_) in enumerate(T) if n=="Key Left Shift"][0],
             "pub const SHIFT_RIGHT: usize = %d;" % [i for i,(n,_,_) in enumerate(T) if n=="Key Right Shift"][0],
             "",
             "pub static BUTTONS: [Btn; BUTTON_COUNT] = ["]
    for name, kind, p in T:
        if kind == "mouse":
            lines.append(f"    Btn::Mouse(MouseButton::{p}), // {name}")
        elif kind == "char":
            lines.append(f"    Btn::Char({rs_char(p[0])}, {rs_char(p[1])}, PhysicalKey::{p[2]}), // {name}")
        elif kind == "named":
            lines.append(f"    Btn::Named(NamedKey::{p[0]}, PhysicalKey::{p[1]}, KeyLocation::{p[2]}), // {name}")
        elif kind == "numch":
            lines.append(f"    Btn::NumChar({rs_char(p[0])}, PhysicalKey::{p[1]}), // {name}")
    lines.append("];")
    open(path, "w").write("\n".join(lines) + "\n")

if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    emit_rs(os.path.join(here, "guest", "src", "input_table.rs"))
    inp = {"name": "Keyboard and Mouse",
           "_comment": "Mouse Left/Middle/Right, then the keyboard. The two axes are the pointer in stage pixels. Buttons are levels; the core turns level changes into Ruffle's key/mouse events at the start of each frame. Wire order is generated by waterbox/input-table.py.",
           "buttons": [n for n, _, _ in T], "axes": AXES}
    if "--json" in sys.argv:
        print(json.dumps(inp, indent=2))
    else:
        print(f"{len(T)} buttons, {len(AXES)} axes -> guest/src/input_table.rs")
