// GENERATED by waterbox/input-table.py - do not edit; edit the table there.
// One entry per button, in waterbox.config's wire order.
use ruffle_core::events::{KeyLocation, MouseButton, NamedKey, PhysicalKey};

pub enum Btn {
    Mouse(MouseButton),
    /// unshifted char, shifted char, physical key
    Char(char, char, PhysicalKey),
    Named(NamedKey, PhysicalKey, KeyLocation),
    /// a numpad key that types a character
    NumChar(char, PhysicalKey),
}

pub const BUTTON_COUNT: usize = 103;
pub const SHIFT_LEFT: usize = 54;
pub const SHIFT_RIGHT: usize = 55;

pub static BUTTONS: [Btn; BUTTON_COUNT] = [
    Btn::Mouse(MouseButton::Left), // Mouse Left Button
    Btn::Mouse(MouseButton::Middle), // Mouse Middle Button
    Btn::Mouse(MouseButton::Right), // Mouse Right Button
    Btn::Char('a', 'A', PhysicalKey::KeyA), // Key A
    Btn::Char('b', 'B', PhysicalKey::KeyB), // Key B
    Btn::Char('c', 'C', PhysicalKey::KeyC), // Key C
    Btn::Char('d', 'D', PhysicalKey::KeyD), // Key D
    Btn::Char('e', 'E', PhysicalKey::KeyE), // Key E
    Btn::Char('f', 'F', PhysicalKey::KeyF), // Key F
    Btn::Char('g', 'G', PhysicalKey::KeyG), // Key G
    Btn::Char('h', 'H', PhysicalKey::KeyH), // Key H
    Btn::Char('i', 'I', PhysicalKey::KeyI), // Key I
    Btn::Char('j', 'J', PhysicalKey::KeyJ), // Key J
    Btn::Char('k', 'K', PhysicalKey::KeyK), // Key K
    Btn::Char('l', 'L', PhysicalKey::KeyL), // Key L
    Btn::Char('m', 'M', PhysicalKey::KeyM), // Key M
    Btn::Char('n', 'N', PhysicalKey::KeyN), // Key N
    Btn::Char('o', 'O', PhysicalKey::KeyO), // Key O
    Btn::Char('p', 'P', PhysicalKey::KeyP), // Key P
    Btn::Char('q', 'Q', PhysicalKey::KeyQ), // Key Q
    Btn::Char('r', 'R', PhysicalKey::KeyR), // Key R
    Btn::Char('s', 'S', PhysicalKey::KeyS), // Key S
    Btn::Char('t', 'T', PhysicalKey::KeyT), // Key T
    Btn::Char('u', 'U', PhysicalKey::KeyU), // Key U
    Btn::Char('v', 'V', PhysicalKey::KeyV), // Key V
    Btn::Char('w', 'W', PhysicalKey::KeyW), // Key W
    Btn::Char('x', 'X', PhysicalKey::KeyX), // Key X
    Btn::Char('y', 'Y', PhysicalKey::KeyY), // Key Y
    Btn::Char('z', 'Z', PhysicalKey::KeyZ), // Key Z
    Btn::Char('1', '!', PhysicalKey::Digit1), // Key 1
    Btn::Char('2', '@', PhysicalKey::Digit2), // Key 2
    Btn::Char('3', '#', PhysicalKey::Digit3), // Key 3
    Btn::Char('4', '$', PhysicalKey::Digit4), // Key 4
    Btn::Char('5', '%', PhysicalKey::Digit5), // Key 5
    Btn::Char('6', '^', PhysicalKey::Digit6), // Key 6
    Btn::Char('7', '&', PhysicalKey::Digit7), // Key 7
    Btn::Char('8', '*', PhysicalKey::Digit8), // Key 8
    Btn::Char('9', '(', PhysicalKey::Digit9), // Key 9
    Btn::Char('0', ')', PhysicalKey::Digit0), // Key 0
    Btn::Char(' ', ' ', PhysicalKey::Space), // Key Space
    Btn::Named(NamedKey::Enter, PhysicalKey::Enter, KeyLocation::Standard), // Key Enter
    Btn::Named(NamedKey::Escape, PhysicalKey::Escape, KeyLocation::Standard), // Key Escape
    Btn::Named(NamedKey::Tab, PhysicalKey::Tab, KeyLocation::Standard), // Key Tab
    Btn::Named(NamedKey::Backspace, PhysicalKey::Backspace, KeyLocation::Standard), // Key Backspace
    Btn::Named(NamedKey::Delete, PhysicalKey::Delete, KeyLocation::Standard), // Key Delete
    Btn::Named(NamedKey::Insert, PhysicalKey::Insert, KeyLocation::Standard), // Key Insert
    Btn::Named(NamedKey::Home, PhysicalKey::Home, KeyLocation::Standard), // Key Home
    Btn::Named(NamedKey::End, PhysicalKey::End, KeyLocation::Standard), // Key End
    Btn::Named(NamedKey::PageUp, PhysicalKey::PageUp, KeyLocation::Standard), // Key Page Up
    Btn::Named(NamedKey::PageDown, PhysicalKey::PageDown, KeyLocation::Standard), // Key Page Down
    Btn::Named(NamedKey::ArrowUp, PhysicalKey::ArrowUp, KeyLocation::Standard), // Key Up
    Btn::Named(NamedKey::ArrowDown, PhysicalKey::ArrowDown, KeyLocation::Standard), // Key Down
    Btn::Named(NamedKey::ArrowLeft, PhysicalKey::ArrowLeft, KeyLocation::Standard), // Key Left
    Btn::Named(NamedKey::ArrowRight, PhysicalKey::ArrowRight, KeyLocation::Standard), // Key Right
    Btn::Named(NamedKey::Shift, PhysicalKey::ShiftLeft, KeyLocation::Left), // Key Left Shift
    Btn::Named(NamedKey::Shift, PhysicalKey::ShiftRight, KeyLocation::Right), // Key Right Shift
    Btn::Named(NamedKey::Control, PhysicalKey::ControlLeft, KeyLocation::Left), // Key Left Control
    Btn::Named(NamedKey::Control, PhysicalKey::ControlRight, KeyLocation::Right), // Key Right Control
    Btn::Named(NamedKey::Alt, PhysicalKey::AltLeft, KeyLocation::Left), // Key Left Alt
    Btn::Named(NamedKey::Alt, PhysicalKey::AltRight, KeyLocation::Right), // Key Right Alt
    Btn::Named(NamedKey::CapsLock, PhysicalKey::CapsLock, KeyLocation::Standard), // Key Caps Lock
    Btn::Named(NamedKey::NumLock, PhysicalKey::NumLock, KeyLocation::Standard), // Key Num Lock
    Btn::Named(NamedKey::ScrollLock, PhysicalKey::ScrollLock, KeyLocation::Standard), // Key Scroll Lock
    Btn::Named(NamedKey::Pause, PhysicalKey::Pause, KeyLocation::Standard), // Key Pause
    Btn::Named(NamedKey::F1, PhysicalKey::F1, KeyLocation::Standard), // Key F1
    Btn::Named(NamedKey::F2, PhysicalKey::F2, KeyLocation::Standard), // Key F2
    Btn::Named(NamedKey::F3, PhysicalKey::F3, KeyLocation::Standard), // Key F3
    Btn::Named(NamedKey::F4, PhysicalKey::F4, KeyLocation::Standard), // Key F4
    Btn::Named(NamedKey::F5, PhysicalKey::F5, KeyLocation::Standard), // Key F5
    Btn::Named(NamedKey::F6, PhysicalKey::F6, KeyLocation::Standard), // Key F6
    Btn::Named(NamedKey::F7, PhysicalKey::F7, KeyLocation::Standard), // Key F7
    Btn::Named(NamedKey::F8, PhysicalKey::F8, KeyLocation::Standard), // Key F8
    Btn::Named(NamedKey::F9, PhysicalKey::F9, KeyLocation::Standard), // Key F9
    Btn::Named(NamedKey::F10, PhysicalKey::F10, KeyLocation::Standard), // Key F10
    Btn::Named(NamedKey::F11, PhysicalKey::F11, KeyLocation::Standard), // Key F11
    Btn::Named(NamedKey::F12, PhysicalKey::F12, KeyLocation::Standard), // Key F12
    Btn::Char('-', '_', PhysicalKey::Minus), // Key Minus
    Btn::Char('=', '+', PhysicalKey::Equal), // Key Equals
    Btn::Char('[', '{', PhysicalKey::BracketLeft), // Key Left Bracket
    Btn::Char(']', '}', PhysicalKey::BracketRight), // Key Right Bracket
    Btn::Char('\\', '|', PhysicalKey::Backslash), // Key Backslash
    Btn::Char(';', ':', PhysicalKey::Semicolon), // Key Semicolon
    Btn::Char('\'', '"', PhysicalKey::Quote), // Key Quote
    Btn::Char(',', '<', PhysicalKey::Comma), // Key Comma
    Btn::Char('.', '>', PhysicalKey::Period), // Key Period
    Btn::Char('/', '?', PhysicalKey::Slash), // Key Slash
    Btn::Char('`', '~', PhysicalKey::Backquote), // Key Backquote
    Btn::NumChar('0', PhysicalKey::Numpad0), // Numpad 0
    Btn::NumChar('1', PhysicalKey::Numpad1), // Numpad 1
    Btn::NumChar('2', PhysicalKey::Numpad2), // Numpad 2
    Btn::NumChar('3', PhysicalKey::Numpad3), // Numpad 3
    Btn::NumChar('4', PhysicalKey::Numpad4), // Numpad 4
    Btn::NumChar('5', PhysicalKey::Numpad5), // Numpad 5
    Btn::NumChar('6', PhysicalKey::Numpad6), // Numpad 6
    Btn::NumChar('7', PhysicalKey::Numpad7), // Numpad 7
    Btn::NumChar('8', PhysicalKey::Numpad8), // Numpad 8
    Btn::NumChar('9', PhysicalKey::Numpad9), // Numpad 9
    Btn::NumChar('+', PhysicalKey::NumpadAdd), // Numpad Add
    Btn::NumChar('-', PhysicalKey::NumpadSubtract), // Numpad Subtract
    Btn::NumChar('*', PhysicalKey::NumpadMultiply), // Numpad Multiply
    Btn::NumChar('/', PhysicalKey::NumpadDivide), // Numpad Divide
    Btn::NumChar('.', PhysicalKey::NumpadDecimal), // Numpad Decimal
    Btn::Named(NamedKey::Enter, PhysicalKey::NumpadEnter, KeyLocation::Numpad), // Numpad Enter
];
